from django.urls import path
from . import views

urlpatterns = [
    path('health', views.health),
    path('auth/login', views.login_view),
    path('auth/register', views.register_view),
    path('auth/dev-login', views.dev_login_view),
    path('auth/refresh', views.refresh_view),
    path('auth/logout', views.logout_view),
    path('auth/me', views.me_view),
    path('auth/strava/connect', views.strava_connect),
    path('auth/strava/signup-connect', views.strava_signup_connect),
    path('auth/strava/signup-prefill', views.strava_signup_prefill),
    path('auth/strava/disconnect', views.strava_disconnect),
    path('auth/strava/sync-profile', views.strava_sync_profile),
    path('auth/strava/callback', views.strava_callback),
    path('strava/sync-now', views.sync_now),
    path('strava/webhook', views.strava_webhook),
    path('activities', views.activities),
    path('activities/<int:pk>', views.activity_detail),
    path('activities/<int:pk>/regenerate-note', views.regenerate),
    path('profile', views.profile),
    path('goal', views.goal_settings),
    path('plan/current-week', views.current_week_plan),
    path('plan/generate-week', views.generate_week_plan),
    path('ai/settings', views.ai_settings),
    path('ai/context-preview', views.ai_context_preview),
    path('ai/onboarding/generate', views.ai_onboarding_generate),
    path('ai/history', views.ai_history),
    path('ai/ask', views.ai_ask),
    path('coach-tone', views.coach_tone_view),
    path('coach-tone/refresh', views.refresh_coach_tone),
    path('next-workout', views.next_workout),
    path('integrations', views.integrations),
    path('integrations/telegram/setup', views.telegram_setup_status),
    path('integrations/telegram/generate-code', views.telegram_generate_code),
    path('integrations/telegram/verify', views.telegram_verify_setup),
    path('integrations/telegram/disconnect', views.telegram_disconnect),
    path('integrations/test-email', views.test_email),
    path('integrations/test-telegram', views.test_telegram),
    path('plan', views.plan),
    path('plan/generate', views.plan),
    path('demo/import', views.import_demo_activity),
]
