# Generated by Django 5.1.5 on 2026-02-26 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strava_activity_id", models.BigIntegerField(unique=True)),
                ("type", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=255)),
                ("start_date", models.DateTimeField()),
                ("distance_m", models.FloatField(default=0)),
                ("moving_time_s", models.IntegerField(default=0)),
                ("elapsed_time_s", models.IntegerField(default=0)),
                ("total_elevation_gain_m", models.FloatField(default=0)),
                ("average_speed_mps", models.FloatField(default=0)),
                ("max_speed_mps", models.FloatField(default=0)),
                ("avg_hr", models.FloatField(blank=True, null=True)),
                ("max_hr", models.FloatField(blank=True, null=True)),
                ("calories", models.FloatField(blank=True, null=True)),
                ("suffer_score", models.FloatField(blank=True, null=True)),
                ("map_summary_polyline", models.TextField(blank=True, null=True)),
                ("raw_payload", models.JSONField(default=dict)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActivityStream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_streams", models.JSONField(default=dict)),
                ("has_latlng", models.BooleanField(default=False)),
                ("has_hr", models.BooleanField(default=False)),
                ("has_cadence", models.BooleanField(default=False)),
                (
                    "activity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.activity"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AthleteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goals", models.CharField(blank=True, max_length=255)),
                ("schedule", models.JSONField(blank=True, default=dict)),
                ("constraints", models.TextField(blank=True)),
                ("injury_notes", models.TextField(blank=True)),
                ("experience_level", models.CharField(blank=True, max_length=64)),
                ("preferred_sports", models.JSONField(blank=True, default=list)),
                ("weekly_target_hours", models.FloatField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoachNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=64)),
                ("prompt_version", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("json_output", models.JSONField(default=dict)),
                ("text_summary", models.TextField()),
                ("tokens_used", models.IntegerField(blank=True, null=True)),
                ("cost_usd_estimate", models.FloatField(blank=True, null=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.activity"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DerivedMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avg_pace_sec_per_km", models.FloatField(blank=True, null=True)),
                ("best_effort_estimates", models.JSONField(default=dict)),
                ("intensity_score", models.FloatField(default=0)),
                ("hr_zone_distribution", models.JSONField(default=dict)),
                (
                    "activity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.activity"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_enabled", models.BooleanField(default=False)),
                ("telegram_enabled", models.BooleanField(default=False)),
                ("email_address", models.EmailField(blank=True, max_length=254)),
                ("telegram_chat_id", models.CharField(blank=True, max_length=64)),
                ("daily_summary_enabled", models.BooleanField(default=False)),
                ("weekly_summary_enabled", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StravaConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("athlete_id", models.BigIntegerField(unique=True)),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                ("expires_at", models.DateTimeField()),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_polled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="active", max_length=32)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("plan_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
