# Generated by Django 6.0.2 on 2026-02-27 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_aifeaturecache'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aifeaturecache',
            new_name='core_aifeat_user_id_c04eb3_idx',
            old_name='core_aifeat_user_id_fa97db_idx',
        ),
        migrations.RenameIndex(
            model_name='aifeaturecache',
            new_name='core_aifeat_updated_f6f9df_idx',
            old_name='core_aifeat_updated_47a448_idx',
        ),
    ]
