# Generated by Django 6.0.2 on 2026-02-28 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_plannedworkout'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='plannedworkout',
            new_name='core_planne_user_id_a8097f_idx',
            old_name='core_planned_user_id_bf7d26_idx',
        ),
        migrations.RenameIndex(
            model_name='plannedworkout',
            new_name='core_planne_user_id_404c6b_idx',
            old_name='core_planned_user_id_b6cb17_idx',
        ),
    ]
