# Generated by Django 6.0.2 on 2026-02-28 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_aichatsession_aichatmessage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aichatmessage',
            new_name='core_aichat_session_5ed922_idx',
            old_name='core_aichat_sessio_6f9138_idx',
        ),
        migrations.RenameIndex(
            model_name='aichatmessage',
            new_name='core_aichat_role_fb2e1b_idx',
            old_name='core_aichat_role_8ccdb5_idx',
        ),
        migrations.RenameIndex(
            model_name='aichatsession',
            new_name='core_aichat_user_id_8a1982_idx',
            old_name='core_aichat_user_id_c6253e_idx',
        ),
        migrations.RenameIndex(
            model_name='personalrecord',
            new_name='core_person_user_id_ef3656_idx',
            old_name='core_persona_user_id_0771e6_idx',
        ),
        migrations.RenameIndex(
            model_name='personalrecord',
            new_name='core_person_user_id_6c613f_idx',
            old_name='core_persona_user_id_8e7dbf_idx',
        ),
    ]
